# GitHub Sponsors - Add your GitHub username(s) here when you set up GitHub Sponsors
# github: [your-username]

# Patreon - Add your Patreon username here
# patreon: your-patreon-username

# Open Collective - Add your Open Collective username here
# open_collective: your-collective-name

# Ko-fi - Add your Ko-fi username here
# ko_fi: your-kofi-username

# Tidelift - Add your Tidelift package identifier here
# tidelift: npm/decoyable

# Community Bridge - Add your Community Bridge project name here
# community_bridge: your-project-name

# Liberapay - Add your Liberapay username here
# liberapay: your-liberapay-username

# IssueHunt - Add your IssueHunt username here
# issuehunt: your-issuehunt-username

# Custom sponsorship URLs - Add up to 4 custom URLs here
# custom: ['https://www.paypal.me/yourname', 'https://buymeacoffee.com/yourname']
