name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov pytest-asyncio httpx

      - name: Run tests
        run: python -m pytest tests/ -v --tb=short || true

      - name: Run coverage (optional)
        run: python -m pytest tests/ --cov=decoyable --cov-report=term || true

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort mypy pre-commit

      - name: Run Ruff linting
        run: ruff check decoyable/ tests/ main.py || true

      - name: Run Black formatting check
        run: black --check decoyable/ tests/ main.py || true

      - name: Run isort check
        run: isort --check-only decoyable/ tests/ main.py || true

      - name: Run MyPy type checking
        run: mypy decoyable/ main.py --ignore-missing-imports || true

  security:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety || true

      - name: Run Bandit security scan
        run: bandit -r decoyable/ --exclude "*/test*,*/tests/*" || true

      - name: Run Safety check
        run: safety check || true

  docker:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t decoyable:test . || true

      - name: Test Docker import
        run: docker run --rm decoyable:test python -c "import decoyable; print('✓ Import successful')" || true

  defense:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov pytest-asyncio httpx bandit safety detect-secrets

      - name: Run defense tests
        run: python -m pytest tests/defense_tests.py -v --tb=short || true

      - name: Run comprehensive security scan
        run: |
          echo "Running Bandit security scan..."
          bandit -r decoyable/ --exclude "*/test*,*/tests/*" -f json -o bandit-report.json || true
          echo "Running Safety dependency check..."
          safety check --json > safety-report.json || true
          echo "Running Detect-secrets scan..."
          detect-secrets scan --all-files > detect-secrets-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
            detect-secrets-report.json

  pre-commit:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files || true
