name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install ruff black mypy pytest pip-audit

      - name: Lint & Type check
        run: |
          ruff check .
          black --check .
          mypy decoyable

      - name: Run tests
        run: pytest -q

      - name: Security audit
        run: pip-audit -r requirements.txt || true
